import re

def parse_pseudo_yaml_to_py(filepath, outpath):
    with open(filepath, 'r') as f:
        content = f.read()

    # Extract all attributes block
    attributes_block = content.split("attributes:")[1]
    
    # Split by the 2-space indented keys
    raw_features = re.split(r'\n  ([a-zA-Z0-9_\-\(\)\.\+]+):\n', "\n" + attributes_block)
    
    # The first element is before the first key, drop it
    raw_features = raw_features[1:]
    
    attributes = {}
    
    for i in range(0, len(raw_features), 2):
        key = raw_features[i]
        block = raw_features[i+1]
        
        feature_dict = {}
        
        # Regex to extract simple keys
        for field in ['canonical_name', 'namespace', 'category', 'data_type']:
            m = re.search(rf'    {field}: (.*)', block)
            if m:
                feature_dict[field] = m.group(1).strip()
                
        # Regex to extract lists
        for field in ['units', 'enumerations']:
            m = re.search(rf'    {field}: \[(.*)\]', block)
            if m:
                items = [x.strip().strip('"').strip("'") for x in m.group(1).split(',')]
                feature_dict[field] = [x for x in items if x]
                
        # Extract synonyms (can be list of strings)
        m = re.search(r'    synonyms: \[(.*)\]', block)
        if m:
            syn_str = m.group(1)
            # Find quoted strings
            synonyms = re.findall(r'"([^"]*)"', syn_str)
            if not synonyms:
                 synonyms = [x.strip().strip("'") for x in syn_str.split(',')]
            feature_dict['synonyms'] = [x for x in synonyms if x]
            
        # Extract template
        m = re.search(r'    template: "(.*)"', block)
        if m:
            feature_dict['template'] = m.group(1).strip()
            
        attributes[key] = feature_dict

    with open(outpath, 'w') as f:
        f.write("# AUTO-GENERATED NATIVE PYTHON DICTIONARY FROM YAML\n")
        f.write("# Do not edit this file directly, edit vehicle_ontology.yaml instead.\n\n")
        f.write("VEHICLE_ONTOLOGY = {\n")
        f.write("    'attributes': {\n")
        
        for k, v in attributes.items():
            f.write(f"        '{k}': {repr(v)},\n")
            
        f.write("    }\n")
        f.write("}\n")

if __name__ == "__main__":
    parse_pseudo_yaml_to_py("src/ontology/vehicle_ontology.yaml", "src/ontology/vehicle_ontology_data.py")
    print("Successfully compiled yaml to native python dict.")
